<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <?php echo $this->headTitle($this->title)->setSeparator(' - ')->setAutoEscape(false)->setDefaultAttachOrder('APPEND')->headTitle('VoteApp') ?>
    <meta name="author" content="Tomasz Skręt">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl(); ?>/css/vote-app.css">

    <?php echo $this->headStyle(); ?>
</head>

<body>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">General Election</h1>
        </div>
    </div>
</div>

<?php echo $this->layout()->content; ?>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <hr/>
            <p>&copy <?php echo date("Y"); ?> Vote App</p>
        </div>
    </div>
</div>
</body>
</html>