<div class="container">
    <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
            <div class="well well-lg">
                <?php echo $this->form; ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
            <a href="<?php echo $this->url(Array('controller' => 'result', 'action' => 'index', 'module' => 'default'), 'default', true); ?>" class="btn btn-info btn-block btn-lg"><i class="glyphicon glyphicon-stats"></i> See results</a>
        </div>
    </div>
</div>