<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-push-3 well well-lg">
            <h2 class="text-center">Your answers have been saved.</h2>
            <a href="<?php echo $this->url(Array('controller' => 'result', 'action' => 'index', 'module' =>'default'), 'default', true); ?>" class="btn btn-primary btn-block btn-lg"><i class="glyphicon glyphicon-stats"></i> See results</a>
            <hr/>
            <a href="<?php echo $this->url(Array('controller' => 'vote', 'action' => 'index', 'module' =>'default'), 'default', true); ?>" class="btn btn-default btn-block btn-lg"><i class="glyphicon glyphicon-pencil"></i> Vote again</a>
        </div>
    </div>
</div>